name: feature-analysis-app
region: waw

# Web Service - główna aplikacja Streamlit
services:
- name: streamlit-app
  github:
    repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
    branch: main
    deploy_on_push: true
  source_dir: /
  build_command: pip install --upgrade pip && pip install -r requirements.txt
  run_command: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs  # $5/miesiąc - wystarczy do startu
  http_port: 8501
  health_check:
    http_path: /_stcore/health
    initial_delay_seconds: 60  # Dłuższy czas dla instalacji PyCaret
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: PYTHONUNBUFFERED
    value: "1"
  - key: PORT
    value: "8501"
  # Zmienne środowiskowe z kluczami API - ustaw w dashboardzie DigitalOcean jako SECRETS
  # W dashboardzie App Platform dodaj jako Environment Variables:
  # - OPENAI_API_KEY (typ: SECRET)
  # - LANGFUSE_PUBLIC_KEY (typ: SECRET)
  # - LANGFUSE_SECRET_KEY (typ: SECRET)
  # - LANGFUSE_HOST (typ: GENERAL, wartość: https://cloud.langfuse.com)

